randr-edid(1)

# NAME

randr-edid - Print EDIDs of attached monitors


# SYNOPSIS

*randr-edid* [_--help_]


# DESCRIPTION

*randr-edid* Prints the EDIDs of attached monitors in KDL format. The format matches
*autorandrd*(5).

# SEE ALSO
*autorandrd*(5), *autorandrd*(1)


# AUTHORS
Maintained by Jimmy Brisson. Up to date sources can be found at
https://github.com/theotherjimmy/autorandr-rs and bugs/patchs may be submitted
through the builtin github issue tracker.
